// Generated by gencpp from file see_n_tell/ContourData.msg
// DO NOT EDIT!


#ifndef SEE_N_TELL_MESSAGE_CONTOURDATA_H
#define SEE_N_TELL_MESSAGE_CONTOURDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace see_n_tell
{
template <class ContainerAllocator>
struct ContourData_
{
  typedef ContourData_<ContainerAllocator> Type;

  ContourData_()
    : data_lengths()
    , data()  {
    }
  ContourData_(const ContainerAllocator& _alloc)
    : data_lengths(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint64_t, typename ContainerAllocator::template rebind<uint64_t>::other >  _data_lengths_type;
  _data_lengths_type data_lengths;

   typedef std::vector<uint64_t, typename ContainerAllocator::template rebind<uint64_t>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::see_n_tell::ContourData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::see_n_tell::ContourData_<ContainerAllocator> const> ConstPtr;

}; // struct ContourData_

typedef ::see_n_tell::ContourData_<std::allocator<void> > ContourData;

typedef boost::shared_ptr< ::see_n_tell::ContourData > ContourDataPtr;
typedef boost::shared_ptr< ::see_n_tell::ContourData const> ContourDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::see_n_tell::ContourData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::see_n_tell::ContourData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace see_n_tell

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'see_n_tell': ['/home/chibike/catkin_ws/src/see_n_tell/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::see_n_tell::ContourData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::see_n_tell::ContourData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::see_n_tell::ContourData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::see_n_tell::ContourData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::see_n_tell::ContourData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::see_n_tell::ContourData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::see_n_tell::ContourData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ebaaef9a06efaba93f1f22be3f7556c2";
  }

  static const char* value(const ::see_n_tell::ContourData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xebaaef9a06efaba9ULL;
  static const uint64_t static_value2 = 0x3f1f22be3f7556c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::see_n_tell::ContourData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "see_n_tell/ContourData";
  }

  static const char* value(const ::see_n_tell::ContourData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::see_n_tell::ContourData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64[]          data_lengths\n\
uint64[]          data\n\
";
  }

  static const char* value(const ::see_n_tell::ContourData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::see_n_tell::ContourData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data_lengths);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ContourData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::see_n_tell::ContourData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::see_n_tell::ContourData_<ContainerAllocator>& v)
  {
    s << indent << "data_lengths[]" << std::endl;
    for (size_t i = 0; i < v.data_lengths.size(); ++i)
    {
      s << indent << "  data_lengths[" << i << "]: ";
      Printer<uint64_t>::stream(s, indent + "  ", v.data_lengths[i]);
    }
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint64_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEE_N_TELL_MESSAGE_CONTOURDATA_H
